{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-test/2.0.10/kotlin-test-2.0.10.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "jvmJUnitApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-2.0.10.jar",
          "url": "kotlin-test-junit-2.0.10.jar",
          "size": 5088,
          "sha512": "c51413650df4f55558a2deec51580c6a7ce4e4352875de1b18bfb68aa78ea7c37994b4b76f61a2160aa2b9b0d10bb7fe219090c3b792a6b461a0729c0a8dcdb5",
          "sha256": "0f2a81be213bfcfb5daf698f004d51793d74b1da2846ba5aa3b2ec119c733b8e",
          "sha1": "7eaacab06bd81489815e532c0ad44ddf4e975957",
          "md5": "bd56c690c0fe3243b409c7a7e954fd7e"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.0.10"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.0.10"
        }
      ]
    },
    {
      "name": "jvmJUnitRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-2.0.10.jar",
          "url": "kotlin-test-junit-2.0.10.jar",
          "size": 5088,
          "sha512": "c51413650df4f55558a2deec51580c6a7ce4e4352875de1b18bfb68aa78ea7c37994b4b76f61a2160aa2b9b0d10bb7fe219090c3b792a6b461a0729c0a8dcdb5",
          "sha256": "0f2a81be213bfcfb5daf698f004d51793d74b1da2846ba5aa3b2ec119c733b8e",
          "sha1": "7eaacab06bd81489815e532c0ad44ddf4e975957",
          "md5": "bd56c690c0fe3243b409c7a7e954fd7e"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.0.10"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.0.10"
        }
      ]
    },
    {
      "name": "jvmJUnitSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-junit-2.0.10-sources.jar",
          "url": "kotlin-test-junit-2.0.10-sources.jar",
          "size": 2830,
          "sha512": "7e646d9971895dd20e122c2a51b0e062d0b03ef898e5886c17baa324ffdb651bf466b7169f828c3dd2f868145ae386f0520b0faa1b7017294742d07e4ebaa4b7",
          "sha256": "c411a0dad1218f3f652b6619f228fefee498903ee6e11c36c990fbc3fe823f18",
          "sha1": "48ca1b92544803c16b9042ae5b5976f6469e0a8c",
          "md5": "ff35307cfd380882a2b7a0d77f06e1b4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.0.10"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.0.10"
        }
      ]
    }
  ]
}